name: Deploy Infra (Bicep)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login no Azure com OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy do Bicep
        run: |
          az deployment group create \
            --resource-group mvpconf \
            --template-file ./function_keyvault_managed_identity.bicep
