name: Deploy Infra (Bicep)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy do Bicep
        run: |
          az deployment group create \
            --resource-group mvpconf \
            --template-file ./function_keyvault_managed_identity.bicep
