name: Deploy Azure Function App Code

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Function App
        run: |
          pip install azure-functions
          func azure functionapp publish mvpconf-blumenau-function --python Function
